//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugador()
        {
            this.Puntaje = new HashSet<Puntaje>();
        }
    
        public int idJugador { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string correo { get; set; }
        public string usuario { get; set; }
        public string contrasenia { get; set; }
        public string key_confirmation { get; set; }
        public Nullable<bool> registro_confirmado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puntaje> Puntaje { get; set; }
    }
}
