//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lisman.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lisman.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, it&apos;s a pleasure that you want to register in the game.
        ///Click on the following link to confirm your email address and finish the process..
        /// </summary>
        public static string body_email {
            get {
                return ResourceManager.GetString("body_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string confirm_pass {
            get {
                return ResourceManager.GetString("confirm_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Game.
        /// </summary>
        public static string exit_game {
            get {
                return ResourceManager.GetString("exit_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifes.
        /// </summary>
        public static string game_lifes {
            get {
                return ResourceManager.GetString("game_lifes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string game_score {
            get {
                return ResourceManager.GetString("game_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string go_back {
            get {
                return ResourceManager.GetString("go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Mode.
        /// </summary>
        public static string history_mode {
            get {
                return ResourceManager.GetString("history_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join a game.
        /// </summary>
        public static string join_game {
            get {
                return ResourceManager.GetString("join_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  joined the game.
        /// </summary>
        public static string joined_game {
            get {
                return ResourceManager.GetString("joined_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string language_english {
            get {
                return ResourceManager.GetString("language_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string language_spanish {
            get {
                return ResourceManager.GetString("language_spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  left the game.
        /// </summary>
        public static string left_game {
            get {
                return ResourceManager.GetString("left_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string log_in {
            get {
                return ResourceManager.GetString("log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string log_out {
            get {
                return ResourceManager.GetString("log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Score Story Mode.
        /// </summary>
        public static string max_score_history {
            get {
                return ResourceManager.GetString("max_score_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Multiplayer Mode Score.
        /// </summary>
        public static string max_score_multiplayer {
            get {
                return ResourceManager.GetString("max_score_multiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To login you have to confirm your account.
        /// </summary>
        public static string message_account_confirm {
            get {
                return ResourceManager.GetString("message_account_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter confirmation password please.
        /// </summary>
        public static string message_error_confirmation_password {
            get {
                return ResourceManager.GetString("message_error_confirmation_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email please.
        /// </summary>
        public static string message_error_email {
            get {
                return ResourceManager.GetString("message_error_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter lastname please.
        /// </summary>
        public static string message_error_lastname {
            get {
                return ResourceManager.GetString("message_error_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name please.
        /// </summary>
        public static string message_error_name {
            get {
                return ResourceManager.GetString("message_error_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password please.
        /// </summary>
        public static string message_error_password {
            get {
                return ResourceManager.GetString("message_error_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords cannot be different.
        /// </summary>
        public static string message_error_passwords_different {
            get {
                return ResourceManager.GetString("message_error_passwords_different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username please.
        /// </summary>
        public static string message_error_usename {
            get {
                return ResourceManager.GetString("message_error_usename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already registered please enter another.
        /// </summary>
        public static string message_exists_email {
            get {
                return ResourceManager.GetString("message_exists_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username already exists please enter antoher.
        /// </summary>
        public static string message_exists_username {
            get {
                return ResourceManager.GetString("message_exists_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email.
        /// </summary>
        public static string message_invalid_email {
            get {
                return ResourceManager.GetString("message_invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid last name please.
        /// </summary>
        public static string message_invalid_lastname {
            get {
                return ResourceManager.GetString("message_invalid_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid name please.
        /// </summary>
        public static string message_invalid_name {
            get {
                return ResourceManager.GetString("message_invalid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No games available.
        /// </summary>
        public static string message_nogames_found {
            get {
                return ResourceManager.GetString("message_nogames_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Failed.
        /// </summary>
        public static string message_registration_error {
            get {
                return ResourceManager.GetString("message_registration_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Registration.
        ///We have sent a confirmation email to your email please enter the link to complete the process..
        /// </summary>
        public static string message_registration_successful {
            get {
                return ResourceManager.GetString("message_registration_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string message_warning_login {
            get {
                return ResourceManager.GetString("message_warning_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer Games Won.
        /// </summary>
        public static string multiplayer_games_won {
            get {
                return ResourceManager.GetString("multiplayer_games_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer Mode.
        /// </summary>
        public static string multiplayer_mode {
            get {
                return ResourceManager.GetString("multiplayer_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string new_game {
            get {
                return ResourceManager.GetString("new_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players Found.
        /// </summary>
        public static string players_found {
            get {
                return ResourceManager.GetString("players_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions Table.
        /// </summary>
        public static string positions_table {
            get {
                return ResourceManager.GetString("positions_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching players.
        /// </summary>
        public static string searching_players {
            get {
                return ResourceManager.GetString("searching_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection error, please try again.
        /// </summary>
        public static string server_connection_error {
            get {
                return ResourceManager.GetString("server_connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string start_game {
            get {
                return ResourceManager.GetString("start_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation email.
        /// </summary>
        public static string subject_email {
            get {
                return ResourceManager.GetString("subject_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string title_main_menu {
            get {
                return ResourceManager.GetString("title_main_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Register.
        /// </summary>
        public static string title_user_register {
            get {
                return ResourceManager.GetString("title_user_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
    }
}
