//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string User { get; set; }
        public string Password { get; set; }
        public string Key_confirmation { get; set; }
        public string Registration_date { get; set; }
    
        public virtual Record Record { get; set; }
        public virtual Player Player { get; set; }
    }
}
