//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityModelContainer : DbContext
    {
        public EntityModelContainer()
            : base("name=EntityModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Jugador> JugadorSet { get; set; }
        public virtual DbSet<Cuenta> CuentaSet { get; set; }
        public virtual DbSet<Historial> HistorialSet { get; set; }
        public virtual DbSet<Partida> PartidaSet { get; set; }
        public virtual DbSet<Chat> ChatSet { get; set; }
        public virtual DbSet<Mensaje> MensajeSet { get; set; }
    }
}
