//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int Id { get; set; }
        public Nullable<int> Multijugador_PuntajeMaximo { get; set; }
        public Nullable<int> Historia_PuntajeMaximo { get; set; }
        public Nullable<int> Mult_PartidasJugadas { get; set; }
        public Nullable<int> Mult_PartidasGanadas { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
    }
}
