//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Id { get; set; }
        public Nullable<int> Mult_best_score { get; set; }
        public Nullable<int> Story_best_score { get; set; }
        public Nullable<int> Mult_games_played { get; set; }
        public Nullable<int> Mult_games_won { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
